server:
  port: 8082

spring:
  application:
    name: employee
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: eidiko
    password: eidiko
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
