server:
 port: 8090

spring:
 application:
  name: TaskApplication
 oracle:
  datasource:
   url: jdbc:oracle:thin:@localhost:1521:xe
   username: eidiko
   password: sarasu10
   driver-class-name: oracle.jdbc.OracleDriver

 mysql:
  datasource:
   url: jdbc:mysql://localhost:3306/root
   username: root
   password: sarasu10
   driver-class-name: com.mysql.cj.jdbc.Driver