server:
  port: 8090
spring:
  application:
   name: actionservice
  datasource:
    username: eidiko
    password: sarasu10
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    compatibility-verifier:
      enabled: false